export const home_aboutus = {
    header_text: 'Expertise That Moves Your Business Forward',
    description: `At Loom Freight, our people bring <strong>37 years of combined professional experience</strong> to a shared commitment: "Delivering dependable logistics and project management solutions."\n We combine practical knowledge with careful planning and responsive communication to support your business at every stage. From individual shipments to complex project requirements, we focus on the details that matter—your timelines, your cargo, and your confidence in our service.`,
    subhead1: 'Our Mission',
    subdesc1: 'To simplify logistics through reliable coordination, efficient solutions, and personal attention. We work to earn lasting trust by communicating clearly, taking responsibility, and treating every client’s priorities as our own.',
    subhead2: 'Verticals We Serve',
    subdesc2: `We provide logistics and project support for the <strong>oil and gas, petrochemical, pharmaceutical, telecommunications, and power sectors</strong>.\n We tailor our approach to each client’s operational requirements, with a focus on safe handling, timely delivery, and coordinated execution.`,
    about_tag1_head: '35+',
    about_tag1_desc: 'yrs of Accumulated Experience',
    about_tag2_head: '1000+',
    about_tag2_desc: 'Projects Completed',
    about_tag3_head: 'Global',
    about_tag3_desc: 'Reach & Operations',
    about_tag4_head: '24/7',
    about_tag4_desc: 'logistics Support',
}